# Generated by Django 3.1.8 on 2021-05-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20210528_1511"),
        ("coop", "0007_auto_20210521_1139"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draftuser",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="country",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="email",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="preferred_language",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="street",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="street_2",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="username",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="birthdate",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="city",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="country",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="email",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="is_company",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="postcode",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="preferred_language",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="street",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="street_2",
        ),
        migrations.AddField(
            model_name="draftuser",
            name="user_info",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.userinfo",
            ),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="user_info",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.userinfo",
            ),
        ),
    ]
