# Generated by Django 3.1.8 on 2021-05-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0008_auto_20210528_1511"),
        ("coop", "0009_auto_20210529_1248"),
    ]

    operations = []
