# Generated by Django 3.1.8 on 2021-05-29 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0010_merge_20210529_1349"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="draftuser",
            name="from_startnext",
        ),
        migrations.RemoveField(
            model_name="draftuser",
            name="is_investing",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="from_startnext",
        ),
        migrations.RemoveField(
            model_name="shareowner",
            name="is_investing",
        ),
    ]
