# Generated by Django 3.1.8 on 2021-06-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coop", "0011_auto_20210529_1349"),
    ]

    operations = [
        migrations.AddField(
            model_name="shareowner",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Company name"
            ),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="is_company",
            field=models.BooleanField(default=False, verbose_name="Is company"),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="is_from_startnext",
            field=models.BooleanField(
                default=False, verbose_name="Comes from Startnext May 2021"
            ),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="is_investing",
            field=models.BooleanField(
                default=False, verbose_name="Is an investing (not active) member"
            ),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="ratenzahlung",
            field=models.BooleanField(default=False, verbose_name="Ratenzahlung"),
        ),
        migrations.AddField(
            model_name="shareowner",
            name="startnext_welcome_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
