[tool.poetry]
name = "tapir"
version = "0.1.0"
description = ""
authors = ["Leon Handreke <leonh@ndreke.de>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "^3.1.7"
django-bootstrap4 = "^2.3.1"
django-ldapdb = "^1.5.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
ipython = "^7.21.0"
pre-commit = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
