# Generated by Django 3.1.8 on 2021-05-29 13:49

from django.db import migrations, models
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_auto_20210528_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="is_investing",
            field=models.BooleanField(
                default=False, verbose_name="Is an investing (not active) member"
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Company name"
            ),
        ),
    ]
