# Generated by Django 3.1.8 on 2021-06-03 13:47

from django.db import migrations
import ldapdb.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_auto_20210529_1349"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="is_company",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="is_from_startnext",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="is_investing",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="is_using_deferred_payments",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="username",
        ),
        migrations.AlterField(
            model_name="ldapgroup",
            name="cn",
            field=ldapdb.models.fields.CharField(
                db_column="cn", max_length=200, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ldapperson",
            name="uid",
            field=ldapdb.models.fields.CharField(
                db_column="uid", max_length=200, primary_key=True, serialize=False
            ),
        ),
    ]
